name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distro: temurin
        java-version: '17'


    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build debug APK
      run: cd android-app && gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-debug-apk
        path: android-app/app/build/outputs/apk/debug/app-debug.apk
